### ISSUE TITLE
causes requests to timeout

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [compumike/hairpin-proxy#13]
I had the same problem with nginx-ingress and cert-manager and tried this solutions however, when i try to curl with the external domain from inside one of my pods it times out
![Screen Shot 2021-04-08 at 10 26 56 PM](https://user-images.githubusercontent.com/36244069/114124207-89035200-98b9-11eb-964a-08f68cfa2e88.png)

both with and without the flag --haproxy-protocol and of course when I curl localhost it works fine

any ideas?

**Comment by compumike** [comment]
Hi @ahmed-adly-khalil, let's see if we can confirm whether the hairpin-proxy itself is working or not. I'd like to isolate whether or not the hairpin-proxy-haproxy is reachable and working, and separate that from the problem of whether the external domain name is being rewritten to point to it.

First, can you check the Coredns configmap to confirm that it's being updated:

```
kubectl get configmap -n kube-system coredns -o=jsonpath='{.data.Corefile}'
```

You should see a line `# Added by hairpin-proxy` corresponding to your external domain name.

Second, can you confirm that the DNS lookup for your external domain name, as seen from one of your pods, actually has changed to match the hairpin-proxy service?

```
kubectl run my-test-container --image=alpine -it --rm -- /bin/sh

# In the container shell:
apk add bind-tools curl
dig subdomain.example.com
dig hairpin-proxy.hairpin-proxy.svc.cluster.local
curl http://your.external.domain/
```

Do these DNS lookups from `dig` match each other?

Third, can you confirm that the hairpin-proxy-haproxy pod is up and running?

```
kubectl get pods -n hairpin-proxy
kubectl logs -n hairpin-proxy deployment/hairpin-proxy-haproxy
```

What happens if you `curl http://hairpin-proxy.hairpin-proxy.svc.cluster.local/` -- I get a 404 (i.e. no matching ingress host).

**Comment by ahmed-adly-khalil** [comment]
Hello @compumike 
Thanks so much for the reply, I followed the debugging steps and got the below error

![Screen Shot 2021-04-09 at 8 07 59 PM](https://user-images.githubusercontent.com/36244069/114253326-66337500-996f-11eb-9ff9-31e0231826a6.png)
i'm not sure what caused `hairpin-proxy-haproxy-79464944cf-dwwls` to crash

when i tried `k logs -n hairpin-proxy hairpin-proxy-haproxy-79464944cf-dwwls`

i got 

```
[WARNING] 099/011123 (1) : config : missing timeouts for frontend 'fe_80'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING] 099/011123 (1) : config : missing timeouts for backend 'be_ingress_80'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING] 099/011123 (1) : config : missing timeouts for frontend 'fe_443'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING] 099/011123 (1) : config : missing timeouts for backend 'be_ingress_443'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[NOTICE] 099/011123 (1) : haproxy version is 2.3.9-53945bf
[ALERT] 099/011123 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:7] : 'server my_server' : could not resolve address 'ingress-nginx-controller.ingress-nginx.svc.cluster.local'.
[ALERT] 099/011123 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:16] : 'server my_server' : could not resolve address 'ingress-nginx-controller.ingress-nginx.svc.cluster.local'.
[ALERT] 099/011123 (1) : Failed to initialize server(s) addr.
```
unfortunately, i don't know how to resolve this, any ideas?

**Comment by ahmed-adly-khalil** [comment]
i think the problem in this error:
```
parsing [/usr/local/etc/haproxy/haproxy.cfg:7] : 'server my_server' : could not resolve address 'ingress-nginx-controller.ingress-nginx.svc.cluster.local'.
```
because my services looks like this: 
```
izzi-staging-nginx-ingress           LoadBalancer   10.128.247.132   45.79.242.192   80:30275/TCP,443:31293/TCP   65m
```
is there a way to override the haproxy config `my_server`?

**Comment by ahmed-adly-khalil** [comment]
update, I looked at the code and was able to override `TARGET_SERVER` as follow:
```

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hairpin-proxy-haproxy
  name: hairpin-proxy-haproxy
  namespace: hairpin-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hairpin-proxy-haproxy
  template:
    metadata:
      labels:
        app: hairpin-proxy-haproxy
    spec:
      containers:
        - image: compumike/hairpin-proxy-haproxy:0.2.1
          name: main
          env:
            - name: TARGET_SERVER
              value: ingress-nginx-controller.izzi-staging-nginx-ingress.svc.cluster.local
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
            limits:
              memory: "200Mi"
              cpu: "50m"

```
However, i'm still getting same error when running `kubectl logs -n hairpin-proxy deployment/hairpin-proxy-haproxy`
```
[WARNING] 099/042242 (1) : config : missing timeouts for frontend 'fe_80'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING] 099/042242 (1) : config : missing timeouts for backend 'be_ingress_80'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING] 099/042242 (1) : config : missing timeouts for frontend 'fe_443'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING] 099/042242 (1) : config : missing timeouts for backend 'be_ingress_443'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[NOTICE] 099/042242 (1) : haproxy version is 2.3.9-53945bf
[ALERT] 099/042242 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:7] : 'server my_server' : could not resolve address 'ingress-nginx-controller.izzi-staging-nginx-ingress.svc.cluster.local'.
[ALERT] 099/042242 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:16] : 'server my_server' : could not resolve address 'ingress-nginx-controller.izzi-staging-nginx-ingress.svc.cluster.local'.
[ALERT] 099/042242 (1) : Failed to initialize server(s) addr.
```
I think i'm using the wrong value, any idea where should i find the correct value?

**Comment by ahmed-adly-khalil** [comment]
@compumike Thanks so much, after lots of debugging and the need to download `ttps://raw.githubusercontent.com/compumike/hairpin-proxy/v0.2.1/deploy.yml` locallly and override `TARGET_SERVER` in `hairpin-proxy-haproxy` as follow: 
```

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hairpin-proxy-haproxy
  name: hairpin-proxy-haproxy
  namespace: hairpin-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hairpin-proxy-haproxy
  template:
    metadata:
      labels:
        app: hairpin-proxy-haproxy
    spec:
      containers:
        - image: compumike/hairpin-proxy-haproxy:0.2.1
          name: main
          env:
            - name: TARGET_SERVER
              value: izzi-staging-nginx-ingress.default.svc.cluster.local
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
            limits:
              memory: "200Mi"
              cpu: "50m"

---
```

now when i run `k exec customer-portal-ui-8d666656f-kxbpc -- curl http://hairpin-proxy.hairpin-proxy.svc.cluster.local/` and `k exec my-pod -- curl http://domain.com` both respond with: 
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.19.9</center>
</body>
</html>
100   157  100   157    0     0  78500      0 --:--:-- --:--:-- --:--:-- 78500
```
also the dig results: 
for `k exec customer-portal-ui-8d666656f-kxbpc -- dig http://domain.com`
```

; <<>> DiG 9.16.11 <<>> http://izzinow.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 24417
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 1b81ebb0cfbffa56 (echoed)
;; QUESTION SECTION:
;http://izzinow.com.		IN	A

;; AUTHORITY SECTION:
com.			30	IN	SOA	a.gtld-servers.net. nstld.verisign-grs.com. 1618030861 1800 900 604800 86400

;; Query time: 4 msec
;; SERVER: 10.128.0.10#53(10.128.0.10)
;; WHEN: Sat Apr 10 05:01:23 UTC 2021
;; MSG SIZE  rcvd: 138

```

and for `k exec my-pod -- dig hairpin-proxy.hairpin-proxy.svc.cluster.local`
```
; <<>> DiG 9.16.11 <<>> hairpin-proxy.hairpin-proxy.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17667
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 48e3c7091b8b5623 (echoed)
;; QUESTION SECTION:
;hairpin-proxy.hairpin-proxy.svc.cluster.local. IN A

;; ANSWER SECTION:
hairpin-proxy.hairpin-proxy.svc.cluster.local. 30 IN A 10.128.234.232

;; Query time: 4 msec
;; SERVER: 10.128.0.10#53(10.128.0.10)
;; WHEN: Sat Apr 10 05:02:04 UTC 2021
;; MSG SIZE  rcvd: 147
```













I hope i will be able to resolve this

Thanks so much
